name: Execute API on PR Label

on:
  pull_request:
    types:
      - labeled

jobs:
  label_triggered:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is added
        id: label_check
        run: echo "::set-output name=label::${{ github.event.label.name }}"

      - name: Perform action based on label
        run: |
          label=${{ steps.label_check.outputs.label }}
          if [ "$label" = "test" ]; then
            curl -X GET https://zipcloud.ibsnet.co.jp/api/search?zipcode=1000011
          fi